/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\sofaSet.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sofaSet.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.004, 0.222, 0.219]}>
        <mesh geometry={nodes.Material2183.geometry} material={materials.Pale_lancelot_oak_PBR} />
        <mesh geometry={nodes.Material2183_1.geometry} material={materials.material_12} />
      </group>
      <mesh geometry={nodes['H-Pic-4'].geometry} material={materials.Summer_Evening} position={[2.764, 1.644, -0.337]} />
      <mesh geometry={nodes['H-Pic-2'].geometry} material={materials.House_With_A_Yellow_Seat} position={[2.764, 3.085, -0.337]} />
      <mesh geometry={nodes['H-Pic-1'].geometry} material={materials['Mid_Century_-_Fallingwater-final']} position={[2.764, 3.085, -1.918]} />
      <mesh geometry={nodes['H-Pic-3'].geometry} material={materials['Mid_Century_-Paraty-House-Brazil']} position={[2.764, 1.644, -1.918]} />
      <group position={[2.76, 1.646, -1.917]}>
        <mesh geometry={nodes.Material2319.geometry} material={materials.material} />
        <mesh geometry={nodes.Material2319_1.geometry} material={materials.Color_008} />
      </group>
      <group position={[-0.548, 0.289, -1.039]} rotation={[0, -0.627, 0]}>
        <mesh geometry={nodes.Material2546.geometry} material={materials.Pale_lancelot_oak_PBR} />
        <mesh geometry={nodes.Material2546_1.geometry} material={materials.PDM_Leather_BandB_AC_Lounge_2} />
      </group>
      <group position={[-0.645, 0.289, 1.385]} rotation={[0, -0.627, 0]}>
        <mesh geometry={nodes.Material2006.geometry} material={materials.Pale_lancelot_oak_PBR} />
        <mesh geometry={nodes.Material2006_1.geometry} material={materials.PDM_Leather_BandB_AC_Lounge_2} />
      </group>
      <group position={[0.814, 0.289, 1.279]} rotation={[0, -0.627, 0]}>
        <mesh geometry={nodes.Material2007.geometry} material={materials.Pale_lancelot_oak_PBR} />
        <mesh geometry={nodes.Material2007_1.geometry} material={materials.PDM_Leather_BandB_AC_Lounge_2} />
      </group>
      <group position={[0.593, 0.289, -1.039]} rotation={[0, -0.627, 0]}>
        <mesh geometry={nodes.Material2009.geometry} material={materials.Pale_lancelot_oak_PBR} />
        <mesh geometry={nodes.Material2009_1.geometry} material={materials.PDM_Leather_BandB_AC_Lounge_2} />
      </group>
      <group position={[2.76, 1.646, -0.335]}>
        <mesh geometry={nodes.Material2026.geometry} material={materials.material} />
        <mesh geometry={nodes.Material2026_1.geometry} material={materials.Color_008} />
      </group>
      <group position={[2.76, 3.087, -0.335]}>
        <mesh geometry={nodes.Material2027.geometry} material={materials.material} />
        <mesh geometry={nodes.Material2027_1.geometry} material={materials.Color_008} />
      </group>
      <group position={[2.76, 3.087, -1.917]}>
        <mesh geometry={nodes.Material2031.geometry} material={materials.material} />
        <mesh geometry={nodes.Material2031_1.geometry} material={materials.Color_008} />
      </group>
    </group>
  )
}

useGLTF.preload('/sofaSet.gltf')
